# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a1eadb180a9423e986b0a4ffd322438ffb810d3dc346375cef4824e4903bc53f4638775acaf9f22687d1a06c71d6612d630b13a685de5958e719fbb29db07d6

test:
  secret_key_base: 20d4fdc39fcce70ff41738a702d8997635780e4c3a80fab1530efda91952b6046a7331554348996229ddaf1b291498a62c3de793b88d31902761037269f90e39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
